name: flutter_pi_2
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 13.0.1+13

environment:
  sdk: ^3.1.1

dependencies:
  change_app_package_name: ^1.2.0
  english_words: ^4.0.0
  flash: ^3.1.1
  flutter:
    sdk: flutter
  flutter_mjpeg: ^2.0.4
  flutter_reactive_ble: ^5.3.1
  flutter_vlc_player: ^7.4.2
  permission_handler: ^11.3.1
  provider: ^6.0.0
  url_launcher: ^6.3.0
  uuid: ^4.4.0
  webview_flutter: ^4.10.0
  wifi_iot: ^0.3.19+1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/croppedlogo.png
    - assets/images/heartrate.gif
    - assets/images/lung.gif
    - assets/images/giphy.webp
    - assets/images/lung2.webp
    - assets/images/laryng.png
